name: RZ-G2UL-images 云编译

on: 
  repository_dispatch:
  workflow_dispatch:
  release:
    types: [published]
  push:
    tags:
    - 'v*'   
jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update && sudo apt-get full-upgrade -y && sudo apt-get upgrade -y && sudo apt-get autoremove -y
        sudo apt-get install gawk wget git-core diffstat unzip texinfo gcc-multilib build-essential chrpath socat cpio python python3 python3-pip python3-pexpect xz-utils debianutils iputils-ping libsdl1.2-dev xterm p7zip-full libyaml-dev python3-git python3-jinja2 libegl1-mesa pylint3python3-subunit mesa-common-dev
    - name: Clone source code
      run: |
        cd /opt
        sudo git clone git://git.yoctoproject.org/poky
        sudo wget https://github.com/LV36/openwrt-ssd20x-toolchian/releases/download/2018.08/wt-gcc-arm-8.2-2018.08-x86_64-arm-linux-gnueabihf.tag.gz
        sudo tar -xvf wt-gcc-arm-8.2-2018.08-x86_64-arm-linux-gnueabihf.tag.gz
        sudo chmod 777 ~/.profile
        echo -e '\nexport PATH=/opt/gcc-arm-8.2-2018.08-x86_64-arm-linux-gnueabihf/bin:$PATH\n' >> ~/.profile
        source ~/.profile
    - name: Build Firmware
      run: |
        cd /opt/openwrt-ssd20x/18.06
        ./scripts/feeds update -a
        ./scripts/feeds install -a -f
        make WT2015_wt
        make V=s -j4
        cd /opt
        sudo tar -czvf Purple-Pi-R1-OpenWrt.tar.gz /opt/openwrt-ssd20x/18.06/bin/targets/sstar/ssd20x/WT2015/*
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Purple-Pi-R1-OpenWrt 
        path: /opt/openwrt-ssd20x/18.06/bin/targets/sstar/ssd20x/WT2015
    - name: Upload firmware to release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "Purple-Pi-R1-OpenWrt"
        files: /opt/Purple-Pi-R1-OpenWrt.tar.gz
